config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get '/signin' => 'sessions#new'
  get '/signup' => 'users#new'
  delete '/signout' => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :create_remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, email: true, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }

  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to users_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = 'Пользователь успешно создан'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Пользователь успешно обновлен'
      redirect_to root_url
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def signed_in_user
    redirect_to signin_url, notice: 'Пожалуйста, войдите на сайт' unless signed_in?
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url, notice: 'Вы не можете редактировать профили других пользователей.') unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EasyAuth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <ul>
    <li><%= link_to 'На главную', root_url %></li>
    <li><%= link_to 'Регистрация', signup_path %></li>
    <% if signed_in? %>
        <li><%= link_to current_user.name, current_user %></li>
        <li><%= link_to 'Выход', signout_path, method: "delete" %></li>
    <% else %>
        <li><%= link_to 'Вход', signin_path %></li>
    <% end %>
  </ul>
</header>
<div>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div>
      Форма содержит ошибки.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |error| %>
      <li>* <%= error %></li>
      <% end %>
    </ul>
<% end %>

app/views/users/edit.html.erb
<h1>Редактирование профиля</h1>

<div>
  <div>
    <%= render 'shared/error_messages' %>
  </div>
  <div>
    <%= form_for(@user) do |f| %>
        <div>
          <%= f.label :name, 'Имя' %>
          <%= f.text_field :name %>
        </div>

        <div>
          <%= f.label :email, 'E-mail' %>
          <%= f.text_field :email %>
        </div>

        <div>
          <%= f.label :password, 'Пароль' %>
          <%= f.password_field :password %>
        </div>

        <div>
          <%= f.label :password_confirmation, 'Подтвердите пароль' %>
          <%= f.password_field :password_confirmation %>
        </div>

        <div>
          <%= f.submit 'Сохранить изменения' %>
        </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Список пользователей</h1>

<div>
  <table border="2px solid black">
    <tr>
      <th>ID</th>
      <th>Имя</th>
      <th>E-mail</th>
      <th>Дата создания</th>
      <th>&nbsp;</th>
    </tr>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at %></td>
      <td><%= link_to 'Изменить', edit_user_path(user.id) %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<h1>Регистрация</h1>

<div>
  <div>
    <%= render 'shared/error_messages' %>
  </div>
  <div>
    <%= form_for(@user) do |f| %>
        <div>
        <%= f.label :name, 'Имя' %>
        <%= f.text_field :name %>
        </div>

        <div>
          <%= f.label :email, 'E-mail' %>
          <%= f.text_field :email %>
        </div>

        <div>
          <%= f.label :password, 'Пароль' %>
          <%= f.password_field :password %>
        </div>

        <div>
          <%= f.label :password_confirmation, 'Подтвердите пароль' %>
          <%= f.password_field :password_confirmation %>
        </div>

        <div>
          <%= f.submit 'Создать аккаунт' %>
        </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <%= @user.name %>, <%= @user.email %>
</div>

<div>
  <%= link_to 'Назад', users_path %>
</div>